### ISSUE TITLE
High RAM usage

### ISSUE THREAD

**Issue by ivan-magky** [lzwme/console-log-colors#2]
import { green } from 'console-log-colors';
console.log(green('Hello World'));

It adds 30MB of RAM usage for my website. I can't use your library because of this

**Comment by renxia** [comment]
Firstly, thank you for your feedback! This is mainly due to the increased support for ansi256.
I will consider your suggestion to make some efforts in optimizing initial memory usage. We may need to strike a balance between speed and memory usage.
If possible, please conduct some testing and experience on the optimized logic version.
